route:
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 1s
  receiver: 'mail'

receivers:
  - name: 'mail'
    email_configs:
      - to: 'nhu.quynh1731@gmail.com'
        from: 'quynhnln1310@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'quynhnln1310@gmail.com'
        auth_identity: 'quynhnln1310@gmail.com'
        auth_password: 'qhcbspqughrsbgwm'

        