global:
  scrape_interval: 1s
  scrape_timeout: 1s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']
rule_files:
  - alert_rules.yml

scrape_configs:
  - job_name: 'services'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  
  - job_name: 'blackbox'
    metrics_path: /probe
    static_configs:
      - targets:
        - http://192.168.2.161/
    params:
      module: [http_2xx]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox-exporter:9115"
